version: '3.3'

services:

    # db:
        # image: postgres:16-alpine
        # volumes:
            # - postgres_data:/var/lib/postgresql/data/
        # env_file:
            # - ./.env.db
  api:
    build: ./api
    command: gunicorn spoll.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/api/staticfiles
      - ./api:/api
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - static_volume:/api/staticfiles
    depends_on:
      - api

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
    # postgres_data:
  static_volume:
