version: '3.3'

services:

  api:
    build: ./api
    command: gunicorn spoll.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/api/staticfiles
      - ./api:/api
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    ports:
      - "8000:80"
    volumes:
      - static_volume:/api/staticfiles
    depends_on:
      - api

volumes:
  static_volume:
