name: Build to ACR and deploy to AKS

env:
  AZURE_CONTAINER_REGISTRY: spollcontainer
  PROJECT_NAME: spoll
  RESOURCE_GROUP: MC_spoll_spollAKS_eastus
  CLUSTER_NAME: spollAKS
  REGISTRY_URL: spollcontainer.azurecr.io

on:
  # Only allow to run manually
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build image on ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_USERNAME }}
    - run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ github.sha }} -f Dockerfile ./api
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ github.sha }}