name: Build to ACR and deploy to AKS

env:
  AZURE_CONTAINER_REGISTRY: spollcontainer
  PROJECT_NAME: spoll
  RESOURCE_GROUP: MC_spoll_spollAKS_eastus
  CLUSTER_NAME: spollAKS
  REGISTRY_URL: spollcontainer.azurecr.io

on:
  # Only allow to run manually
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build image on ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_URL }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - run: |
        docker build -t ${{ env.REGISTRY_URL }}/api-${{ env.PROJECT_NAME }}:${{ github.sha }} ./api
        docker push ${{ env.REGISTRY_URL }}/api-${{ env.PROJECT_NAME }}:${{ github.sha }}
        docker build -t ${{ env.REGISTRY_URL }}/front-${{ env.PROJECT_NAME }}:${{ github.sha }} -f ./nginx/Dockerfile.prod .
        docker push ${{ env.REGISTRY_URL }}/front-${{ env.PROJECT_NAME }}:${{ github.sha }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.PROJECT_NAME }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy ACR to AKS
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        image: ${{ env.REGISTRY_URL }}/front-${{ env.PROJECT_NAME }}:${{ github.sha }}
        registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        name: front-${{ env.PROJECT_NAME }}
        location: east us

